#line 2 "c_lexer.c"

#line 4 "c_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[279] =
    {   0,
       27,   23,   24,   26,   19,   24,   26,   25,   26,16406,
       23,   24,   26,   24,   26,   24,   26,   10,   23,   24,
       26,   10,   24,   26,   24,   26,   21,   24,   26,   10,
       24,   26,   10,   24,   26,   23,   24,   26,   10,   24,
       26,   14,   24,   26,   14,   24,   26,   14,   24,   26,
        9,   24,   26,   11,   24,   26,    9,   24,   26,   13,
       24,   26,   24,   26,   13,   24,   26,   13,   24,   26,
       13,   24,   26,   13,   24,   26,   13,   24,   26,   13,
       24,   26,   13,   24,   26,   13,   24,   26,   13,   24,
       26,   13,   24,   26,   13,   24,   26,   13,   24,   26,

       13,   24,   26,   13,   24,   26,   13,   24,   26,   13,
       24,   26,   18,   24,   26,   10,   24,   26,    6,   26,
        5,   26,    2,   26,   26,    2,   26,   19, 8214,   25,
    16406,    9,   16,   10,   16,   14,   14,   14,   15,    1,
        4,   15,   14,   14,   20,   14,   10,   13,   13,   13,
       13,   14,   13,   13,   13,   13,   13,    7,   13,   13,
       13,   13,   13,   13,    8,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   14,   13,
       14,    3,   14,   14,   14,   15,   14,   14,   14,   10,
       13,   13,   13,   14,   13,   13,   13,   13,   13,   13,

       13,   13,   13,    7,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   14,   15,   14,   13,   13,    7,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   17,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   12,   13,    7,
       13,   13,   13,   13,   13,   13,   13,   13
    } ;

static const flex_int16_t yy_accept[228] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    5,    8,
       11,   14,   16,   18,   22,   25,   27,   30,   33,   36,
       39,   42,   45,   48,   51,   54,   57,   60,   63,   65,
       68,   71,   74,   77,   80,   83,   86,   89,   92,   95,
       98,  101,  104,  107,  110,  113,  116,  119,  121,  123,
      125,  126,  128,  129,  130,  132,  133,  133,  134,  135,
      135,  136,  136,  137,  138,  139,  139,  139,  140,  141,
      142,  143,  144,  145,  146,  146,  147,  147,  147,  147,
      148,  149,  150,  151,  153,  154,  155,  156,  157,  158,
      160,  161,  162,  163,  164,  165,  167,  168,  169,  170,

      171,  172,  173,  174,  175,  176,  177,  178,  180,  182,
      183,  184,  185,  186,  186,  187,  188,  188,  189,  190,
      191,  191,  192,  193,  195,  196,  197,  198,  199,  200,
      201,  202,  203,  204,  206,  207,  208,  209,  210,  211,
      212,  213,  214,  215,  216,  217,  218,  219,  220,  221,
      222,  224,  224,  225,  225,  226,  226,  226,  226,  226,
      226,  226,  226,  227,  228,  230,  231,  232,  233,  234,
      235,  236,  237,  238,  239,  240,  241,  242,  243,  244,
      245,  246,  247,  248,  249,  250,  250,  250,  250,  250,
      251,  251,  251,  251,  252,  252,  253,  254,  255,  256,

      256,  257,  258,  259,  260,  261,  262,  263,  264,  265,
      266,  266,  266,  266,  267,  268,  269,  270,  272,  273,
      274,  275,  276,  277,  278,  279,  279
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       10,   11,   12,   10,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   10,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   26,
       24,   24,   24,   24,   24,   27,   24,   24,   24,   24,
       24,   24,   24,   24,   27,   24,   24,   24,   24,   24,
       28,    1,   29,    1,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   24,   40,   41,   42,   43,
       44,   45,   24,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[57] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    4,    5,    1,    6,    6,    6,    6,    7,
        1,    1,    1,    8,    8,    8,    8,    1,    9,    8,
        6,    6,    6,    6,    6,    6,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    1,    1
    } ;

static const flex_int16_t yy_base[239] =
    {   0,
        0,    0,  297,  294,   54,   55,  294, 1052,  275,    0,
      267,  223,  231,  213,   51,  225, 1052,  205,   53,   44,
       65,   92,  131,   61,   60,  198,   61,   66, 1052,   68,
       74,   83,   69,  103,   98,  110,  120,  132,  102,  140,
      137,   95,  141,  148,  176, 1052,   42, 1052, 1052, 1052,
     1052,  172,  182, 1052,    0, 1052,  169,  165, 1052,  153,
      150,  181,  199,  187,  205,   76,    0,  239, 1052, 1052,
      243,    0,   79, 1052,  169,  225,  233,  253,  273,  112,
      149,  252,  268,  294,  295,  205,  298,  304,  305,  316,
      320,  322,  331,  334,  338,  243,  340,  354,  356,  357,

      363,  374,  375,  378,  393,  396,  405,  254,  271, 1052,
      400,  426,  407,  442, 1052,  452,  398,  423,  446, 1052,
      466,  460,  419,  150,  461,  471,  477,  480,  481,  483,
      497,  501,  504,  513,  520,  522,  523,  524,  538,  547,
      541,  550,  559,  561,  568,  571,  577,  586,  593,  597,
      595,  615,  629,  395,  602,  640,  677,  650,  671,  103,
      611,  714,  643,  642,  682,  653,  683,  707,  724,  708,
      731,  735,  733,  742,  749,  756,  765,  753,  767,  774,
      783,  785,  786,  792,  801,  705,  213,    0,  536, 1052,
      100,  810,  612,  802,  829,  813,  822,  825,  824,  124,

      841,  844,  845,  848,  855,  862,  866,  872,  878,  881,
      886,  656,  889,  903,  906,   98,  909,  912,  913,  927,
      928,  930,  931,  946,  948, 1052,  983,  992, 1001, 1010,
     1019, 1024, 1027,   68, 1032, 1035,   62, 1043
    } ;

static const flex_int16_t yy_def[239] =
    {   0,
      226,    1,  227,  227,  228,  228,  226,  226,  226,  229,
      226,  226,  230,  226,  226,  231,  226,  226,  226,  226,
      226,  232,  232,   23,  226,  226,  226,  233,  226,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  229,  226,  230,  230,  226,  231,
      231,  226,  226,  226,  226,  226,  234,  226,  226,  226,
      226,   23,   23,  226,  232,   23,  232,  232,  232,  226,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,

      233,  233,  233,  233,  233,  233,  233,   45,   45,  226,
      226,  226,  234,  226,  226,   23,  232,   79,   79,  226,
      235,  233,  233,   84,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
       45,  226,  226,  232,   79,  226,  226,  226,  226,  236,
      236,  236,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  232,  226,  237,  226,  226,
      236,  236,  162,  233,  232,  233,  233,  233,  233,  238,

      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      226,  237,  236,  233,  233,  238,  233,  233,  233,  233,
      233,  233,  233,  233,  233,    0,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226
    } ;

static const flex_int16_t yy_nxt[1109] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   19,   20,   21,   22,   23,   23,   24,    8,
       25,   26,   27,   28,   28,   28,   28,   29,   29,   28,
       30,   31,   32,   33,   34,   35,   36,   28,   37,   28,
       38,   28,   28,   28,   28,   39,   40,   41,   42,   43,
       44,   45,   28,   28,   46,   47,   51,   51,   56,   68,
       68,   68,   68,   59,   52,   52,   62,  212,   63,   64,
       64,   65,   59,  113,   59,   69,   73,   73,   73,   70,
       80,   56,   56,   80,   66,   74,   59,   74,   74,   84,
       84,  112,  112,   74,   73,   73,   73,   56,   82,  226,

       82,   82,   74,   89,   67,   71,   82,   72,   72,   72,
       73,   74,   90,   86,   74,   82,   83,   74,   76,   85,
       87,   74,   74,   77,   78,  200,   88,   82,  190,   74,
       82,  190,   76,  120,   82,   82,   99,  105,   93,   74,
       76,   94,   82,   79,   71,   91,   72,   72,   72,   73,
       74,   74,   82,   95,   92,   96,   74,   76,   61,   74,
       74,   61,   97,   78,   82,   81,   81,   74,   74,   82,
       58,   76,   82,   82,   58,   98,  121,  100,  101,   76,
       82,   82,  226,   53,  106,  107,  110,  102,   74,  104,
      103,  108,  108,  108,  108,   74,   68,   68,   68,   68,

       71,   78,   64,   64,   64,   65,  108,  108,  109,  108,
      108,  108,   71,  111,   64,   64,   64,   65,   71,   56,
       65,   65,   65,   65,   74,  111,   59,  111,  211,  211,
       66,  111,  121,   61,   59,  111,   58,   82,  226,  111,
       75,   75,   75,   75,   56,  111,  226,  111,  116,  116,
       67,  126,   74,  111,   68,   68,   68,   68,   68,   68,
       68,   68,   74,  114,  115,   78,  226,  114,  115,   55,
      121,   74,   74,  114,  115,   82,   53,  114,  115,  121,
      124,  121,  122,  117,   82,   78,  226,   74,  118,  118,
      118,  118,   74,  226,  124,  121,   49,  124,  121,   49,

       82,  151,  124,  118,  118,  119,  118,  118,  118,   84,
       84,  124,  226,   74,   74,  123,  226,   74,  226,  124,
      124,  121,  121,   74,   74,  121,   82,   82,  127,  125,
       82,  121,  121,  226,  124,   74,   82,   82,  226,   74,
      129,   74,  124,  121,  226,  226,  128,  121,   82,  121,
       74,  226,   82,   74,   82,  226,  226,   74,  121,   74,
      226,  121,  226,   82,  130,  121,   82,  121,  131,  132,
       82,  226,   82,   74,  133,   74,   74,  226,  226,  134,
      226,  121,   74,  121,  121,  135,   82,  134,   82,   82,
      121,  226,  137,   74,   74,   82,  136,   74,  226,  140,

      139,  121,  121,  138,  142,  121,   82,   82,  226,  226,
       82,  226,   74,  144,   74,   74,  141,   74,  226,  143,
      121,  226,  145,  121,   74,   82,  111,   78,   82,  186,
       78,  146,  121,  111,  148,  226,  149,   82,   74,  147,
      111,  112,  112,  150,  154,  226,  121,  111,  111,   76,
      226,   82,  111,  152,  152,  111,  226,  153,  153,  153,
      153,  226,  134,   76,  226,  226,  111,  116,  116,   75,
       75,   76,   76,  226,  111,  226,  155,  156,  156,   74,
       74,  157,  158,  158,  159,  226,   76,  121,  121,  226,
       74,  164,   82,   82,   76,  226,   74,  161,  121,   74,

       74,  226,   74,   82,  121,  165,  163,  121,  121,   82,
      121,  168,   82,   82,  169,   82,   74,  162,  226,  226,
       74,  226,  134,   74,  121,  226,  166,  167,  121,   82,
      226,  121,   74,   82,  171,  170,   82,  226,  134,   74,
      121,   74,   74,   74,  226,   82,  226,  121,  226,  121,
      121,  121,   82,  226,   82,   82,   82,   74,  134,  226,
       74,  173,  189,  172,  190,  121,   74,  226,  121,   74,
       82,  226,  174,   82,  121,  177,  189,  121,   74,   82,
       74,  226,   82,  175,  189,  226,  121,   74,  121,  176,
       74,   82,  226,   82,  226,  121,   74,  178,  121,  226,

       82,  226,  181,   82,  121,   74,  226,  179,  180,   82,
      226,  226,   74,  121,  182,  183,   74,  226,   82,  134,
      121,  124,  121,  184,  121,   82,  192,  192,   76,   82,
      153,  153,  153,  153,  226,  124,  226,  185,  213,  190,
      226,  163,   76,  124,  153,  153,  153,  153,  154,  226,
       76,  226,  213,  226,  115,  157,  158,  158,  159,  226,
      213,   74,   74,  226,  115,  158,  158,  158,  159,  121,
      121,  187,   74,  226,   82,   82,  189,  194,  190,  226,
      121,  134,  189,  195,  190,   82,  159,  159,  159,  159,
      189,  188,  158,  158,  158,  159,  189,  189,  189,  190,

      134,   74,   74,  189,  189,  190,  195,  226,  187,  121,
      121,  189,  226,  226,   82,   82,  226,  189,  226,  189,
      226,  196,  226,  226,   74,  189,   74,   74,  188,  193,
      193,  193,  193,  226,  121,  121,  200,   78,  226,   82,
       82,  226,  190,   74,  193,  193,  193,  193,  193,  193,
       74,  121,   74,  199,   74,  197,   82,  226,  121,  226,
      121,   74,  121,   82,  198,   82,  226,   82,   74,  121,
      226,  226,   74,  226,   82,   74,  121,  226,  134,  201,
      121,   82,  226,  121,   74,   82,   74,  202,   82,  226,
      203,  205,  121,   74,  121,  226,  134,   82,  226,  206,

      226,  121,   74,  195,   74,   74,  207,  226,  204,  226,
      121,   74,  121,  121,  226,   82,  208,   82,   82,  121,
       74,   74,  209,  226,   82,  192,  192,  134,  121,  121,
      195,  226,   74,   82,   82,  134,  213,  226,  190,  210,
      121,   74,  226,   74,   74,   82,  226,  226,   74,  121,
      213,  121,  121,  226,   82,  214,   82,   82,  213,  134,
       74,   78,  215,   74,   74,  226,  134,   74,  121,  226,
      226,  121,  121,   82,   74,  121,   82,   82,  134,  226,
       82,   74,  121,  134,  226,   74,  134,  218,  217,  121,
      226,   74,  122,  121,   82,  226,  122,   74,   82,  121,

       74,  211,  211,   96,   82,  121,  219,  226,  121,  134,
       82,  226,  189,   82,  190,  213,  226,  190,  226,  221,
      220,  226,   74,  226,  226,   74,  189,  226,   74,  213,
      121,   74,   74,  121,  189,   82,  121,  213,   82,  121,
      121,   82,  122,  223,   82,   82,   74,   74,  134,   74,
       74,  222,  226,  134,  121,  121,  226,  121,  121,   82,
       82,  224,   82,   82,  134,   74,  226,   74,  225,  226,
      226,  226,  226,  121,  226,  121,  134,  226,   82,  134,
       82,  226,  134,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   50,   50,   50,   50,   50,   50,   50,   50,

       50,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       57,   57,  226,   57,   57,   57,   57,   57,   57,   60,
       60,  226,   60,   60,   60,   60,   60,   60,   75,   75,
       75,   75,   81,   81,   81,  160,  226,  160,  226,  160,
      191,  226,  191,  191,  216,  226,  226,  226,  216,  226,
      216,    7,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,

      226,  226,  226,  226,  226,  226,  226,  226
    } ;

static const flex_int16_t yy_chk[1109] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    6,   15,   20,
       20,   20,   20,   47,    5,    6,   19,  237,   19,   19,
       19,   19,   15,  234,   19,   21,   24,   24,   24,   21,
       25,   25,   27,   27,   19,   28,   21,   30,   33,   31,
       31,   66,   66,   31,   73,   73,   73,   47,   28,  216,

       30,   33,   32,   33,   19,   22,   31,   22,   22,   22,
       22,   22,   33,   32,   42,   32,   30,   35,   22,   31,
       32,   39,   34,   22,   22,  200,   32,   42,  191,   36,
       35,  160,   22,   80,   39,   34,   39,   42,   35,   37,
       22,   35,   36,   22,   23,   34,   23,   23,   23,   23,
       23,   38,   37,   36,   34,   37,   41,   23,   61,   40,
       43,   60,   37,   23,   38,  124,  124,   44,   81,   41,
       58,   23,   40,   43,   57,   38,   81,   40,   40,   23,
       44,   81,   75,   53,   43,   44,   52,   40,   75,   41,
       40,   45,   45,   45,   45,   45,   62,   62,   62,   62,

       64,   75,   64,   64,   64,   64,   45,   45,   45,   45,
       45,   45,   63,   64,   63,   63,   63,   63,   65,   26,
       65,   65,   65,   65,   86,   63,   18,   64,  187,  187,
       63,   65,   86,   16,   14,   64,   13,   86,   76,   63,
       76,   76,   76,   76,   12,   65,   77,   63,   77,   77,
       63,   86,   77,   65,   68,   68,   68,   68,   71,   71,
       71,   71,   96,   68,   68,   77,   78,   71,   71,   11,
       96,   82,   78,   68,   68,   96,    9,   71,   71,   82,
      108,  108,   82,   78,   82,   78,   79,   83,   79,   79,
       79,   79,   79,    7,  108,   83,    4,  109,  109,    3,

       83,  109,  108,   79,   79,   79,   79,   79,   79,   84,
       84,  109,    0,   84,   85,   83,    0,   87,    0,  109,
       84,   84,   85,   88,   89,   87,   84,   85,   87,   85,
       87,   88,   89,    0,   84,   90,   88,   89,    0,   91,
       89,   92,   84,   90,    0,    0,   88,   91,   90,   92,
       93,    0,   91,   94,   92,    0,    0,   95,   93,   97,
        0,   94,    0,   93,   90,   95,   94,   97,   91,   92,
       95,    0,   97,   98,   93,   99,  100,    0,    0,   94,
        0,   98,  101,   99,  100,   95,   98,   97,   99,  100,
      101,    0,   99,  102,  103,  101,   98,  104,    0,  101,

      100,  102,  103,   99,  102,  104,  102,  103,  154,    0,
      104,  117,  105,  103,  154,  106,  101,  117,    0,  102,
      105,    0,  104,  106,  107,  105,  111,  154,  106,  154,
      117,  105,  107,  113,  106,    0,  106,  107,  123,  105,
      111,  112,  112,  107,  117,    0,  123,  113,  111,  118,
        0,  123,  112,  114,  114,  113,    0,  114,  114,  114,
      114,    0,  123,  118,    0,  116,  112,  116,  116,  116,
      116,  118,  119,    0,  112,    0,  119,  121,  121,  122,
      125,  121,  121,  121,  121,    0,  119,  122,  125,    0,
      126,  125,  122,  125,  119,    0,  127,  121,  126,  128,

      129,    0,  130,  126,  127,  126,  122,  128,  129,  127,
      130,  129,  128,  129,  130,  130,  131,  121,    0,    0,
      132,    0,  127,  133,  131,    0,  128,  128,  132,  131,
        0,  133,  134,  132,  133,  132,  133,    0,  131,  135,
      134,  136,  137,  138,    0,  134,    0,  135,    0,  136,
      137,  138,  135,    0,  136,  137,  138,  139,  136,    0,
      141,  137,  189,  135,  189,  139,  140,    0,  141,  142,
      139,    0,  138,  141,  140,  141,  189,  142,  143,  140,
      144,    0,  142,  139,  189,    0,  143,  145,  144,  140,
      146,  143,    0,  144,    0,  145,  147,  142,  146,    0,

      145,    0,  145,  146,  147,  148,    0,  143,  144,  147,
        0,    0,  149,  148,  146,  147,  150,    0,  148,  148,
      149,  151,  151,  149,  150,  149,  161,  161,  155,  150,
      152,  152,  152,  152,    0,  151,    0,  150,  193,  161,
        0,  151,  155,  151,  153,  153,  153,  153,  155,    0,
      155,    0,  193,    0,  153,  156,  156,  156,  156,    0,
      193,  164,  163,    0,  153,  158,  158,  158,  158,  164,
      163,  156,  166,    0,  164,  163,  158,  163,  158,    0,
      166,  164,  212,  165,  212,  166,  159,  159,  159,  159,
      158,  156,  157,  157,  157,  157,  212,  159,  158,  159,

      166,  165,  167,  157,  212,  157,  186,    0,  157,  165,
      167,  159,    0,    0,  165,  167,    0,  157,  186,  159,
        0,  167,    0,    0,  186,  157,  168,  170,  157,  162,
      162,  162,  162,    0,  168,  170,  172,  186,    0,  168,
      170,    0,  162,  169,  162,  162,  162,  162,  162,  162,
      171,  169,  173,  170,  172,  168,  169,    0,  171,    0,
      173,  174,  172,  171,  169,  173,    0,  172,  175,  174,
        0,    0,  178,    0,  174,  176,  175,    0,  171,  173,
      178,  175,    0,  176,  177,  178,  179,  174,  176,    0,
      176,  178,  177,  180,  179,    0,  175,  177,    0,  179,

        0,  180,  181,  194,  182,  183,  180,    0,  177,    0,
      181,  184,  182,  183,    0,  181,  181,  182,  183,  184,
      185,  194,  183,    0,  184,  192,  192,  182,  185,  194,
      195,    0,  196,  185,  194,  185,  192,    0,  192,  184,
      196,  197,  195,  199,  198,  196,    0,    0,  195,  197,
      192,  199,  198,    0,  197,  196,  199,  198,  192,  198,
      201,  195,  197,  202,  203,    0,  199,  204,  201,    0,
        0,  202,  203,  201,  205,  204,  202,  203,  203,    0,
      204,  206,  205,  204,    0,  207,  202,  205,  201,  206,
        0,  208,  206,  207,  206,    0,  207,  209,  207,  208,

      210,  211,  211,  207,  208,  209,  208,    0,  210,  206,
      209,    0,  211,  210,  211,  213,    0,  213,    0,  210,
      209,    0,  214,    0,    0,  215,  211,    0,  217,  213,
      214,  218,  219,  215,  211,  214,  217,  213,  215,  218,
      219,  217,  218,  217,  218,  219,  220,  221,  219,  222,
      223,  214,    0,  215,  220,  221,    0,  222,  223,  220,
      221,  220,  222,  223,  222,  224,    0,  225,  221,    0,
        0,    0,    0,  224,    0,  225,  223,    0,  224,  224,
      225,    0,  225,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  228,  228,  228,  228,  228,  228,  228,  228,

      228,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      230,  230,    0,  230,  230,  230,  230,  230,  230,  231,
      231,    0,  231,  231,  231,  231,  231,  231,  232,  232,
      232,  232,  233,  233,  233,  235,    0,  235,    0,  235,
      236,    0,  236,  236,  238,    0,    0,    0,  238,    0,
      238,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,

      226,  226,  226,  226,  226,  226,  226,  226
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "c_lexer.l"
#define YY_NO_INPUT 1
#line 4 "c_lexer.l"
#include <stdio.h>
#include <stdbool.h>
#include <assert.h>

typedef struct
{
  int line; // Строка
  int column; // Столбец
} Position_t;

extern FILE* result;
static Position_t Position = {1, 1}; //Текущая позиция в файле
static bool GotError = false;// и

// Функция сдвига на num строк
static void incrLine(int num) {Position.line += num;}
// Функция возвращает номер текущей строки в читаемом файле
static int line(void) {return Position.line;}
// Функция сдвига на num столбцов
static void incrColumn(int num) {Position.column += num;}
// Функция возвращает номер текущего столбца в читаемом файле
static int column(void) {return Position.column;}
// Функция сброса номера текущего столбца в читаемом файле в начало
// строки
static void dropColumn(void) {Position.column = 1;}

#define YY_USER_ACTION { incrColumn(yyleng); }

static void printLexeme(const char * tokName)
{
  fprintf(result,"%s, \"%s\", %d, %d\n", tokName, yytext, line(), column() - yyleng);
}

#line 847 "c_lexer.c"

#line 849 "c_lexer.c"

#define INITIAL 0
#define COMMENT_LINE 1
#define COMMENT_BLOCK 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 55 "c_lexer.l"

#line 1074 "c_lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 227 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1052 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 56 "c_lexer.l"
{ BEGIN(COMMENT_BLOCK); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 57 "c_lexer.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 58 "c_lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "c_lexer.l"
{ BEGIN(COMMENT_LINE); }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 61 "c_lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "c_lexer.l"
{ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 64 "c_lexer.l"
{ printLexeme("KEYWORD");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "c_lexer.l"
{ printLexeme("CONDITION OPERATOR"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 68 "c_lexer.l"
{ printLexeme("COMPARE OPERATOR"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "c_lexer.l"
{printLexeme("ARITHMETIC OPERATOR");}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 72 "c_lexer.l"
{ printLexeme("ASSIGN OPERATOR"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "c_lexer.l"
{printLexeme("UNCONDITION JUMP OPERATOR"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 76 "c_lexer.l"
{ printLexeme("IDENTIFIER"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "c_lexer.l"
{printLexeme("INT CONST");}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 80 "c_lexer.l"
{printLexeme("FLOAT CONST");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 82 "c_lexer.l"
{ printLexeme("STRING LITERAL"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 84 "c_lexer.l"
{ printLexeme("INDEXING VARIABLE"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 86 "c_lexer.l"
{ printLexeme("BLOCK OPERATOR"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 88 "c_lexer.l"
{}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "c_lexer.l"
{ printLexeme("LABLE"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 92 "c_lexer.l"
{ printLexeme("DELIMITER");}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 94 "c_lexer.l"
{ dropColumn(); incrLine(1);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 96 "c_lexer.l"
{ printLexeme("ERROR"); GotError = true;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 98 "c_lexer.l"
{ printLexeme("UNKNOWN"); }
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 100 "c_lexer.l"
{ return GotError;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 101 "c_lexer.l"
ECHO;
	YY_BREAK
#line 1287 "c_lexer.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(COMMENT_LINE):
			case YY_STATE_EOF(COMMENT_BLOCK):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 227 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 227 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 226);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 101 "c_lexer.l"

